//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtOtomasyonuWinUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GirisCikis
    {
        public int GirisCikisID { get; set; }
        public Nullable<int> OgrenciID { get; set; }
        public int IslemId { get; set; }
        public System.DateTime Tarih { get; set; }
    
        public virtual Ogrenci Ogrenci { get; set; }
        public virtual Islem Islem { get; set; }
    }
}
