//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtOtomasyonuWinUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odeme
    {
        public int OdemeID { get; set; }
        public Nullable<int> OgrenciID { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public Nullable<System.DateTime> OdemeTarihi { get; set; }
        public Nullable<int> Ay { get; set; }
        public Nullable<int> Yil { get; set; }
    
        public virtual Ogrenci Ogrenci { get; set; }
    }
}
