//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtOtomasyonuWinUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenci()
        {
            this.GirisCikis = new HashSet<GirisCikis>();
            this.IzinBasvuru = new HashSet<IzinBasvuru>();
            this.Odeme = new HashSet<Odeme>();
        }
    
        public int OgrenciID { get; set; }
        public string TCno { get; set; }
        public string AdSoyad { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<int> OdaID { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GirisCikis> GirisCikis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzinBasvuru> IzinBasvuru { get; set; }
        public virtual Oda Oda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odeme> Odeme { get; set; }
    }
}
