//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtOtomasyonuWinUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel()
        {
            this.GelirGider = new HashSet<GelirGider>();
        }
    
        public int PersonelID { get; set; }
        public string AdSoyad { get; set; }
        public string TCno { get; set; }
        public string Telefon { get; set; }
        public string Gorev { get; set; }
        public string Yetki { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GelirGider> GelirGider { get; set; }
    }
}
