//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtOtomasyonuWinUI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YurtOtomasyonuEntities : DbContext
    {
        public YurtOtomasyonuEntities()
            : base("name=YurtOtomasyonuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GelirGider> GelirGider { get; set; }
        public virtual DbSet<GirisCikis> GirisCikis { get; set; }
        public virtual DbSet<Islem> Islem { get; set; }
        public virtual DbSet<IzinBasvuru> IzinBasvuru { get; set; }
        public virtual DbSet<Oda> Oda { get; set; }
        public virtual DbSet<Odeme> Odeme { get; set; }
        public virtual DbSet<Ogrenci> Ogrenci { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
